model:
  name: clouds
  author: Qiana Yang
  version: AA1
  description: ## ADD
  tags:
    - classifier
    - housing
  dependencies: requirements.txt
save_data:
  html: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  local_path: data/raw_cloud.data
  attempt: 4
  wait: 3
load_data:
  input_path: data/raw_cloud.data
  output_path: tests/data/cloud.csv
  columns:
    ['visible_mean', 'visible_max', 'visible_min',
    'visible_mean_distribution', 'visible_contrast',
    'visible_entropy', 'visible_second_angular_momentum',
    'IR_mean', 'IR_max', 'IR_min']
generate_features:
  train_feature_path: tests/data/train_features.csv
  train_target_path: tests/data/train_labels.csv
  test_feature_path: tests/data/test_features.csv
  test_target_path: tests/data/test_labels.csv
  random_state: 42
  test_size: 0.4
train_model:
  method: xgboost
  choose_features:
    features_to_use: [ZN, INDUS, CHAS, NOX, RM, AGE, DIS, RAD, TAX, PTRATIO]
  get_target:
    target: CRIM
  params:
    max_depth: 100
    learning_rate: 50
    random_state: 1019
  fit:
    eval_metric: auc
    verbose: True
  save_tmo: models/example-boston-crime-prediction.pkl
evaluate_model:
  metrics: [auc, accuracy, logloss]
pyfileA:
    functionA:
        variableAA: value
        variableAB: value
    functionB:
        variableBA: value
        variableBB: value
    save_results: path/to/saveoutput.csv