model:
  name: clouds
  author: Qiana Yang
  version: AA1
  description: ## ADD
  tags:
    - classifier
    - housing
  dependencies: requirements.txt
save_data:
  html: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  local_path: data/raw_cloud.data
  attempt: 4
  wait: 3
load_data:
  input_path: data/raw_cloud.data
  output_path: tests/data/cloud.csv
  columns:
    ['visible_mean', 'visible_max', 'visible_min',
    'visible_mean_distribution', 'visible_contrast',
    'visible_entropy', 'visible_second_angular_momentum',
    'IR_mean', 'IR_max', 'IR_min']
generate_features:
  feature_gen:
    features_output_path: tests/data/raw_features.csv
    labels_output_path: tests/data/raw_labels.csv
  add_log_entropy:
    output_path: tests/data/features_log_entropy.csv
  add_entropy_x_contrast:
    output_path: tests/data/features_entropy_x_contrast.csv
  add_ir_range:
    output_path: tests/data/features_ir_range.csv
  add_ir_norm_range:
    output_path: tests/data/features_ir_norm_range.csv
train_model:
  train_test_split:
    train_feature_path: tests/data/train_features.csv
    train_target_path: tests/data/train_labels.csv
    test_feature_path: tests/data/test_features.csv
    test_target_path: tests/data/test_labels.csv
    random_state: 42
    test_size: 0.4
  features: ['log_entropy', 'IR_norm_range', 'entropy_x_contrast']
  model_params:
    n_estimators: 10
    max_depth: 10
    random_state: 42
evaluate_model:
  output_path: tests/result/result.txt
