model:
  name: clouds
  author: Qiana Yang
  version: AA1
  description: a random forest modeling pipeline that classifies clouds.
  dependencies: requirements.txt
save_data:
  html: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  attempt: 4
  wait: 3
load_data:
  columns:
    ['visible_mean', 'visible_max', 'visible_min',
    'visible_mean_distribution', 'visible_contrast',
    'visible_entropy', 'visible_second_angular_momentum',
    'IR_mean', 'IR_max', 'IR_min']
generate_features:
  feature_gen:
    features_output_path: data/raw_features.csv
    labels_output_path: data/raw_labels.csv
  add_log_entropy:
    output_path: data/features_log_entropy.csv
  add_entropy_x_contrast:
    output_path: data/features_entropy_x_contrast.csv
  add_ir_range:
    output_path: data/features_ir_range.csv
  add_ir_norm_range:
    output_path: data/features_ir_norm_range.csv
train_model:
  train_test_split:
    seed: 42
    test_size: 0.4
  fit_model:
    features_list: ['log_entropy', 'IR_norm_range', 'entropy_x_contrast']
  model_params:
    n_estimators: 10
    max_depth: 10
    random_state: 42
